// generated by directives_generate.go; DO NOT EDIT

package plugin

import (
	// Include all plugins.
	_ "github.com/coredns/caddy/onevent"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/any"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/bind"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/bufsize"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/cache"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/cancel"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/chaos"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/debug"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/errors"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/forward"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/hosts"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/log"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/reload"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/tls"
	_ "github.com/inverse-inc/wireguard-go/dns/plugin/trace"
)
