// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wgrpc.proto

package wgrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb1742ce9418ce3, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LastError            string   `protobuf:"bytes,2,opt,name=lastError,proto3" json:"lastError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb1742ce9418ce3, []int{1}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusReply) GetLastError() string {
	if m != nil {
		return m.LastError
	}
	return ""
}

type PeerReply struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerReply) Reset()         { *m = PeerReply{} }
func (m *PeerReply) String() string { return proto.CompactTextString(m) }
func (*PeerReply) ProtoMessage()    {}
func (*PeerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb1742ce9418ce3, []int{2}
}

func (m *PeerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerReply.Unmarshal(m, b)
}
func (m *PeerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerReply.Marshal(b, m, deterministic)
}
func (m *PeerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerReply.Merge(m, src)
}
func (m *PeerReply) XXX_Size() int {
	return xxx_messageInfo_PeerReply.Size(m)
}
func (m *PeerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerReply.DiscardUnknown(m)
}

var xxx_messageInfo_PeerReply proto.InternalMessageInfo

func (m *PeerReply) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *PeerReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PeerReply) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type PeersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersRequest) Reset()         { *m = PeersRequest{} }
func (m *PeersRequest) String() string { return proto.CompactTextString(m) }
func (*PeersRequest) ProtoMessage()    {}
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb1742ce9418ce3, []int{3}
}

func (m *PeersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersRequest.Unmarshal(m, b)
}
func (m *PeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersRequest.Marshal(b, m, deterministic)
}
func (m *PeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersRequest.Merge(m, src)
}
func (m *PeersRequest) XXX_Size() int {
	return xxx_messageInfo_PeersRequest.Size(m)
}
func (m *PeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersRequest proto.InternalMessageInfo

type PeersReply struct {
	Peers                []*PeerReply `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PeersReply) Reset()         { *m = PeersReply{} }
func (m *PeersReply) String() string { return proto.CompactTextString(m) }
func (*PeersReply) ProtoMessage()    {}
func (*PeersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb1742ce9418ce3, []int{4}
}

func (m *PeersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersReply.Unmarshal(m, b)
}
func (m *PeersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersReply.Marshal(b, m, deterministic)
}
func (m *PeersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersReply.Merge(m, src)
}
func (m *PeersReply) XXX_Size() int {
	return xxx_messageInfo_PeersReply.Size(m)
}
func (m *PeersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersReply.DiscardUnknown(m)
}

var xxx_messageInfo_PeersReply proto.InternalMessageInfo

func (m *PeersReply) GetPeers() []*PeerReply {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "StatusReply")
	proto.RegisterType((*PeerReply)(nil), "PeerReply")
	proto.RegisterType((*PeersRequest)(nil), "PeersRequest")
	proto.RegisterType((*PeersReply)(nil), "PeersReply")
}

func init() {
	proto.RegisterFile("wgrpc.proto", fileDescriptor_2fb1742ce9418ce3)
}

var fileDescriptor_2fb1742ce9418ce3 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xec, 0x07, 0xad, 0xdd, 0xb7, 0x6d, 0x85, 0x3d, 0x48, 0x08, 0x1e, 0xca, 0x9e, 0x02, 0xc2,
	0x1e, 0xea, 0x2f, 0x50, 0x91, 0x5e, 0x25, 0x3d, 0x08, 0x82, 0x87, 0xb4, 0x79, 0x68, 0x20, 0xba,
	0xeb, 0xdb, 0x8d, 0xe2, 0xbf, 0x6f, 0xb2, 0xf9, 0x3e, 0xce, 0xcc, 0x63, 0x66, 0xde, 0x00, 0xff,
	0xfb, 0x20, 0x73, 0x56, 0x86, 0xb4, 0xd3, 0xf2, 0x1a, 0x36, 0x47, 0x97, 0xb8, 0xc2, 0xc6, 0xf8,
	0x53, 0xa0, 0x75, 0xf2, 0x09, 0x78, 0x4b, 0x98, 0xfc, 0x5f, 0xdc, 0xc0, 0xd2, 0x7a, 0x18, 0x4c,
	0x77, 0xd3, 0x88, 0xc5, 0x0d, 0x12, 0xb7, 0xc0, 0xf2, 0xc4, 0xba, 0x67, 0x22, 0x4d, 0xc1, 0xcc,
	0x4b, 0x3d, 0x21, 0xdf, 0x81, 0xbd, 0x20, 0x52, 0x6d, 0x51, 0x9e, 0x66, 0xe6, 0x21, 0x4d, 0x09,
	0x6d, 0xeb, 0xd2, 0x13, 0x83, 0x80, 0xd9, 0x28, 0x20, 0x84, 0xd5, 0xa7, 0xb6, 0xee, 0x3b, 0xf9,
	0xc2, 0x60, 0xee, 0x95, 0x0e, 0xcb, 0x2d, 0xac, 0x2b, 0xfb, 0xae, 0xb3, 0x02, 0x68, 0x70, 0x95,
	0xb7, 0x83, 0x85, 0xa9, 0x50, 0x99, 0x35, 0x8f, 0xf8, 0x1e, 0x54, 0x57, 0x25, 0xae, 0x85, 0xfd,
	0x09, 0xd8, 0xeb, 0xe1, 0x88, 0xf4, 0x9b, 0x9d, 0x51, 0xdc, 0x01, 0x3b, 0xa0, 0xab, 0x7f, 0x16,
	0x5b, 0x35, 0x5a, 0x23, 0x5c, 0xab, 0xc1, 0x18, 0x72, 0x22, 0x22, 0x58, 0x95, 0xc7, 0x3e, 0x4c,
	0x6c, 0xd4, 0xb0, 0x44, 0xc8, 0x55, 0xdf, 0x41, 0x4e, 0x1e, 0xaf, 0xde, 0x16, 0x7e, 0xe7, 0xd3,
	0xd2, 0x0f, 0x7d, 0x7f, 0x09, 0x00, 0x00, 0xff, 0xff, 0x82, 0x7d, 0xe7, 0x7e, 0x77, 0x01, 0x00,
	0x00,
}
